plugin:
    has_options: true
    icon: res_simu_si.png
    resources:
        -
            class: CPASimUSante\ItemSelectorBundle\Entity\ItemSelector
            name: cpasimusante_itemselector
            is_exportable: false
            icon: res_simu_si.png
