parameters:
    # Form types
    cpasimusante_itemselector.form.type.itemselector.class: CPASimUSante\ItemSelectorBundle\Form\ItemSelectorType

    # Listeners
    cpasimusante_itemselector.listener.itemselector.class: CPASimUSante\ItemSelectorBundle\Listener\ItemSelectorListener
