services:
# ItemSelector controller
    cpasimusante_itemselector.controller.itemselector:
        class: CPASimUSante\ItemSelectorBundle\Controller\ItemSelectorController
        calls:
            - [ setContainer, [ @service_container ]]
        arguments:
            itemSelectorManager: @cpasimusante_itemselector.manager.itemselector

# ItemSelector controller
    cpasimusante_itemselector.controller.mainconfig:
        class: CPASimUSante\ItemSelectorBundle\Controller\MainConfigController
        calls:
            - [ setContainer, [ @service_container ]]
