services:
# ItemSelector controller
  cpasimusante_itemselector.controller.itemselector:
    class: %cpasimusante_itemselector.controller.itemselector.class%
    calls:
      - [ setContainer, [ @service_container ]]
    arguments:
      itemSelectorManager: @cpasimusante_itemselector.manager.itemselector

    # ItemSelector controller
    cpasimusante_itemselector.controller.mainconfig:
        class: %cpasimusante_itemselector.controller.mainconfig.class%
        calls:
            - [ setContainer, [ @service_container ]]
