services:
    # Administration
    cpasimusante_itemselector.manager.plugin.itemselector:
        class: CPASimUSante\ItemSelectorBundle\Manager\ItemSelectorManager
        arguments:
            om: @claroline.persistence.object_manager
