services:
    # Administration
    cpasimusante_itemselector.manager.plugin.itemselector:
        class: CPASimUSante\ItemSelectorBundle\Manager\ItemSelectorManager
        arguments:
            em: @doctrine.orm.entity_manager
